### ISSUE TITLE
displayCloseButton has no effects

### ISSUE THREAD

**Issue by codwam** [suzuki-0000/SKPhotoBrowser#101]
1、
self.displayCloseButton = false// has no effects
self.enableSingleTapDismiss = true

2、Counld you add a pagecontrol at the bottom?

3、init(originImage: UIImage, photos: [SKPhotoProtocol], animatedFromView: UIView)
should add a similar method originImages: [UIImage], which can be Zoom in originImage?

Wait for you answer...

**Comment by suzuki-0000** [comment]
hi @codwam 

1. I tried ussing both `displayCloseButton` and `enableSingleTapDismiss`, I worked.
![displayclose](https://cloud.githubusercontent.com/assets/1096585/15530803/7ba71fb8-2291-11e6-85df-ede7f7646577.gif)

2. I don't have considering of it now, because we should consider many things( what if its over device width, etc)

3. I don't exactly understand what you want to do, but you can use zooming animation for using  `init(originImage: UIImage, photos: [SKPhotoProtocol], animatedFromView: UIView)`

**Comment by codwam** [comment]
Thanks a lot
