### ISSUE TITLE
Error: Array index out of range

### ISSUE THREAD

**Issue by frisovanderwerf** [suzuki-0000/SKPhotoBrowser#19]
Hi,

I have images in my collection view which I get from (Facebook) JSON. If I write `self.images.append(SKPhoto.photoWithImage(imageView.image!))`, with `imageView.image!` as my image from JSON data, the Photo Browser works, but it doesn't work properly. For example: when I click on an image, it sometimes shows the next/another image and the displayCounterLabel doesn't give the correct information (the total count is wrong, the count of the selected photo is wrong, it says it's the last photo when there're still photos left). 

If I don't write `self.images.append(SKPhoto.photoWithImage(imageView.image!))` in my code, when I click a photo, it first seems like it's gonna work, but then soon (when the view isn't completely loaded yet) there's an error, saying: "Array index out of range"...

Can you please help me as soon as possible?

If I have to provide more code or something, please let me know!

Thanks in advance!

**Comment by frisovanderwerf** [comment]
Maybe it has something to do with my cache, because my JSON doesn't cache and the photos reload every time the page is being scrolled. But I don't know how to fix this haha

**Comment by krummler** [comment]
Hello Friso,

This does sound like a loading problem, since the images are changing from underneath the gallery. Could you clarify by creating an example?
Currently the library API does not support changing sets of images, but rather expects a fixed set when initialising.

Correct me if I'm wrong but I think the only think you'd really need is a way to 'force reload' the gallery contents at a later moment?

**Comment by alexsanderkhitev** [comment]
@krummler I think that this issue needs to close
