### ISSUE TITLE
Save pic to phone collection

### ISSUE THREAD

**Issue by jonhsnow** [suzuki-0000/SKPhotoBrowser#5]
Is there any possibilities to save picture into phone collection? For example add "save" button or anything else?

**Comment by suzuki-0000** [comment]
I think I can add, but need some times. 
pull request is always welcome!

**Comment by ZhangWW** [comment]
i want this feature 2:)

**Comment by pj4533** [comment]
Rather than adding a save button, why not add custom actions, similar to how IDMPhotoBrowser works:  https://github.com/ideaismobile/IDMPhotoBrowser#toolbar

That way it is more flexible.  It could be used to save by adding a 'Save Photo', then calling back to `photoBrowser:didDismissActionSheetWithButtonIndex:photoIndex:`

This leaves the implementation of saving up to the user of SKPhotoBrowser, but keeps SKPhotoBrowser cleaner and more flexible.

**Comment by suzuki-0000** [comment]
@ZhangWW, @jonhsnow 
now  saving pic and other function for control photo implemented at [here](https://github.com/suzuki-0000/SKPhotoBrowser/pull/12) by @pj4533. 
you can try it at latest master, or v1.3.0.

**Comment by pj4533** [comment]
And, note it isn't left to the user to implement.  The default is to provide image saving, but also includes ability to have custom action sheets.  So should give saving functionality with no work.
